version: '3.3'

services:
    api:
        build: ./src
        command:
            - daphne messenger.asgi:application --bind 0.0.0.0
        restart: on-failure
        env_file:
            -   ./.env.local
        depends_on:
            - db
            - redis
        ports:
            - "8000:8000"

    db:
        image: postgres:15.2
        restart: on-failure
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=POSTGRES_USER
            - POSTGRES_PASSWORD=POSTGRES_PASSWORD
            - POSTGRES_DB=POSTGRES_NAME
        healthcheck:
            test: pg_isready -U POSTGRES_NAME -d POSTGRES_NAME
            interval: 30s
            timeout: 3s
            retries: 3

    redis:
        image: redis:7.0.9
        restart: on-failure
        ports:
          - "6379:6379"
        healthcheck:
            test: redis-cli ping
            interval: 30s
            timeout: 10s
            retries: 3

volumes:
    postgres_data: