@startuml
entity Chat {
* pk
__
*created_at: datetime <<generated>>
updated_at: datetime <<generated>>
*is_dialog: bool
}

entity Attachment {
* pk
__
*created_at: datetime <<generated>>
updated_at: datetime <<generated>>
chat_id: number <<FK>>
file: filefield
}

entity Message {
* pk
__
*author_id: number <<FK>>
*chat_id: number <<FK>>
reply_to: number <<FK>>
text: text
forward_by: number <<FK>>
*sent_at: datetime <<generated>>
}

entity User {
* pk
__
*email: text
*password: text
*registered_at: datetime <<generated>>
name: text
surname: text
updated_at: datetime
profile_picture: imagefield
}

entity ChatUser {
* pk
__
* chat_id: Number <<FK>>
* user_id: Number <<FK>>
* role: enum
}


ChatUser }|-- User
ChatUser }|-- Chat


Message }|-- User
Message }|-- Chat

Attachment }|-- Chat

Message ||--|| Message
@enduml