# Generated by Django 4.1.7 on 2023-03-17 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(
                default=False, verbose_name="Пользователь удален"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="author",
            field=models.ForeignKey(
                on_delete=models.SET("DELETED_USER"),
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправитель",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="forwarded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET("DELETED_USER"),
                related_name="forwarded_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кем сообщение было переслано",
            ),
        ),
    ]
