# Generated by Django 4.1.7 on 2023-03-29 08:17

import stdimage.models
import stdimage.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_user_is_deleted_alter_chat_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                null=True,
                upload_to="user_profile_pictures",
                variations={"thumbnail": {"height": 100, "width": 100}},
                verbose_name="Фотография профиля",
            ),
        ),
        migrations.RemoveField(
            model_name="message",
            name="picture",
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.CharField(default=2, max_length=255, verbose_name="Текст сообщения"),
            preserve_default=False,
        ),
    ]
