# Generated by Django 4.1.7 on 2023-03-28 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_user_is_deleted_alter_chat_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="picture",
        ),
    ]
