# Generated by Django 4.1.7 on 2023-04-11 08:50

import core.utils.enums
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="type",
            field=models.CharField(
                choices=[("PICTURE", "PICTURE"), ("FILE", "FILE")],
                default=core.utils.enums.AttachmentTypeEnum["FILE"],
                max_length=100,
                verbose_name="Тип вложения",
            ),
        ),
    ]
