# Generated by Django 4.1.7 on 2023-03-31 11:57

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                null=True,
                upload_to="user_profile_pictures",
                variations={"thumbnail": {"height": 100, "width": 100}},
                verbose_name="Фотография профиля",
            ),
        ),
    ]
