# Generated by Django 4.1.7 on 2023-03-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_message_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.CharField(default=2, max_length=255, verbose_name="Текст сообщения"),
            preserve_default=False,
        ),
    ]
