# Generated by Django 4.1.7 on 2023-04-14 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_attachment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="user",
        ),
        migrations.AddField(
            model_name="attachment",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=models.SET("DELETED_USER"),
                related_name="attachments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправитель",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attachment",
            name="forwarded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET("DELETED_USER"),
                related_name="forwarded_attachments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кем переслано вложение",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="reply_to_attachment",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET("DELETED_ATTACHMENT"),
                related_name="replied_attachments_by_attachment",
                to="core.attachment",
                verbose_name="Вложение, на которое ответили",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="reply_to_message",
            field=models.ForeignKey(
                null=True,
                on_delete=models.SET("DELETED_MESSAGE"),
                related_name="replied_messages_by_attachment",
                to="core.message",
                verbose_name="Сообщение, на которое ответили",
            ),
        ),
    ]
