DELETED_USER = "DELETED_USER"
DELETED_MESSAGE = "DELETED_MESSAGE"
DELETED_ATTACHMENT = "DELETED_ATTACHMENT"

YOU_CANNOT_SET_THE_ROLE_OF_OTHERS_USERS_OF_THIS_CHAT = "You cannot set the role of other users of this chat"
OWNER_ROLE_IS_IMMUTABLE = "Owner role is immutable"
OWNER_IS_NOT_ALLOWED_AS_CHOICE = "Owner is not allowed as choice"
YOU_HAVE_NO_PERMISSION_TO_DELETE_USER = "You have no permission to delete user"
YOU_CANNOT_DELETE_CHAT_OWNER = "You cannot delete chat owner"
ONLY_ADMIN_OR_OWNER_CAN_ADD_USERS_TO_CHAT = "Only admin or owner can add users to chat"
