name: push check

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build containers
        run: docker compose -f docker-compose.ci.yml -p messenger build --build-arg DEV_DEPS=True
      - name: Up containers
        run: docker compose -f docker-compose.ci.yml -p messenger up -d --remove-orphans
      - name: Lint
        run: |
          docker exec -i messenger-api-1 mypy .
          docker exec -i messenger-api-1 black --check .
          docker exec -i messenger-api-1 isort -- check-only .
      - name: run tests
        run: docker exec -i some_prefix-api-1 pytest
      - name: Down containers
        run: docker compose -f docker-compose.ci.yml -p messenger down -v